UmbracoLearning/Models/Navigation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UmbracoLearning.Models
{
    public class NavigationLinkInfo
    {
        public string Text { get; set; }
        public string Url { get; set; }
        public bool NewWindow { get; set; }
        public string Target { get { return NewWindow ? "_blank" : null; } }
        public string Title { get; set; }

        public NavigationLinkInfo() { }
        public NavigationLinkInfo(string url = null, string text = null,
            bool newWindow = false, string title = null)
        {
            Text = text;
            Url = url;
            NewWindow = newWindow;
            Title = title;
        }
    }

    public class NavigationList
    {
        public string Text { get; set; }
        public NavigationLinkInfo Link { get; set; }
        public List<NavigationList> NavItems { get; set; }
        public bool HasSubNavigation { get { return NavItems != null && NavItems.Any() && NavItems.Count > 0; } }

        public NavigationList() { }
        public NavigationList(NavigationLinkInfo link)
        {
            Link = link;
        }
    }
}

UmbracoLearning/Controllers/ElementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace UmbracoLearning.Controllers
{
    public class ElementsController: SurfaceController
    {
        private const string Partial_Views_Path = "~/Views/Partials/Elements/";
        public ActionResult ElementsMainContent()
        {
            return PartialView($"{Partial_Views_Path}ElementsMainContent.cshtml");
        }
    }
}

UmbracoLearning/Controllers/GenericController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace UmbracoLearning.Controllers
{
    public class GenericController: SurfaceController
    {
        private const string Partial_Views_Path = "~/Views/Partials/Generic/";
        public ActionResult GenericMainContent()
        {
            return PartialView($"{Partial_Views_Path}GenericMainContent.cshtml");
        }
    }
}

UmbracoLearning/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace UmbracoLearning.Controllers
{
    public class HomeController: SurfaceController
    {
        private const string Partial_Views_Path = "~/Views/Partials/Home/";
        public ActionResult Banner()
        {
            return PartialView($"{Partial_Views_Path}Banner.cshtml");
        }

        public ActionResult SectionOne()
        {
            return PartialView($"{Partial_Views_Path}SectionOne.cshtml");
        }
        public ActionResult SectionTwo()
        {
            return PartialView($"{Partial_Views_Path}SectionTwo.cshtml");
        }
        public ActionResult SectionThree()
        {
            return PartialView($"{Partial_Views_Path}SectionThree.cshtml");
        }
    }
}

UmbracoLearning/Controllers/SiteSharedLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using UmbracoLearning.Models;
using Umbraco.Core.Models;

namespace UmbracoLearning.Controllers
{
    public class SiteSharedLayoutController : SurfaceController
    {
        private const string Partial_Views_Path = "~/Views/Partials/SharedLayout/";
        public ActionResult Header()
        {
            List<NavigationList> nav = GetNavigationModel();
            return PartialView($"{Partial_Views_Path}Header.cshtml",nav);
        }
        public ActionResult Footer()
        {
            return PartialView($"{Partial_Views_Path}Footer.cshtml");
        }

        //Step 1: create function to get the navigation model from database
        //Step 2: write the code to get the sub navigation
        //Step 3: update the code for header

        public List<NavigationList> GetNavigationModel()
        {
            int pageId = int.Parse(CurrentPage.Path.Split(',')[1]); // There is the page position in path
            IPublishedContent pageInfo = Umbraco.Content(pageId);
            var nav = new List<NavigationList>
            {
                new NavigationList(new NavigationLinkInfo(pageInfo.Url,pageInfo.Name))
            };
            nav.AddRange(GetSubNavigationList(pageInfo));
            //add range of nav(parent & child)
            return nav;
        }

        public List<NavigationList> GetSubNavigationList(dynamic page)
        {
            List<NavigationList> navList = null;
            var subPages = page.Children.Where("Visible");
            if (subPages != null && subPages.Any() && subPages.Count() > 0)
            {
                navList = new List<NavigationList>();
                foreach (var subPage in subPages)
                {
                    var listItem = new NavigationList(new NavigationLinkInfo(subPage.Url, subPage.Name))
                    {
                        NavItems = GetSubNavigationList(subPage)
                    };
                    navList.Add(listItem);
                }
            }
            return navList;
        }

    }
}

UmbracoLearning/Views/BaseTemplate.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

<!DOCTYPE HTML>
<html>
<head>
    <title>Introspect by TEMPLATED</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link href="~/Assests/css/main.css" rel="stylesheet" />
</head>
<body>

    <!-- Header -->
    @{Html.RenderAction("Header", "SiteSharedLayout"); }
    <a href="#menu" class="navPanelToggle"><span class="fa fa-bars"></span></a>

    @RenderBody()
   

    <!-- Footer -->
    @{Html.RenderAction("Footer", "SiteSharedLayout"); }


    <!-- Scripts -->
    <script src="~/Assests/js/jquery.min.js"></script>
    <script src="~/Assests/js/skel.min.js"></script>
    <script src="~/Assests/js/util.js"></script>
    <script src="~/Assests/js/main.js"></script>

</body>
</html>

UmbracoLearning/Views/Elements.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "BaseTemplate.cshtml";
}

@{Html.RenderAction("ElementsMainContent", "Elements"); }

UmbracoLearning/Views/Generic.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "BaseTemplate.cshtml";
}

@{Html.RenderAction("GenericMainContent", "Generic"); }

UmbracoLearning/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "BaseTemplate.cshtml";
}

<!-- Banner -->

@{Html.RenderAction("Banner", "Home"); }

<!-- One -->

@{Html.RenderAction("SectionOne", "Home"); }

<!-- Two -->

@{Html.RenderAction("SectionTwo", "Home"); }

<!-- Three -->

@{Html.RenderAction("SectionThree", "Home"); }

UmbracoLearning/Views/Partials/Generic/GenericMainContent.cshtml
<section id="main">
    <div class="inner">
        <header class="major special">
            <h1>Generic</h1>
            <p>Lorem ipsum dolor sit amet nullam id egestas urna aliquam</p>
        </header>
        <a href="#" class="image fit"><img src="images/pic11.jpg" alt="" /></a>
        <p>Vis accumsan feugiat adipiscing nisl amet adipiscing accumsan blandit accumsan sapien blandit ac amet faucibus aliquet placerat commodo. Interdum ante aliquet commodo accumsan vis phasellus adipiscing. Ornare a in lacinia. Vestibulum accumsan ac metus massa tempor. Accumsan in lacinia ornare massa amet. Ac interdum ac non praesent. Cubilia lacinia interdum massa faucibus blandit nullam. Accumsan phasellus nunc integer. Accumsan euismod nunc adipiscing lacinia erat ut sit. Arcu amet. Id massa aliquet arcu accumsan lorem amet accumsan.</p>
        <p>Amet nibh adipiscing adipiscing. Commodo ante vis placerat interdum massa massa primis. Tempus condimentum tempus non ac varius cubilia adipiscing placerat lorem turpis at. Aliquet lorem porttitor interdum. Amet lacus. Aliquam lobortis faucibus blandit ac phasellus. In amet magna non interdum volutpat porttitor metus a ante ac neque. Nisi turpis. Commodo col. Interdum adipiscing mollis ut aliquam id ante adipiscing commodo integer arcu amet Ac interdum ac non praesent. Cubilia lacinia interdum massa faucibus blandit nullam. Accumsan phasellus nunc integer. Accumsan euismod nunc adipiscing lacinia erat ut sit. Arcu amet. Id massa aliquet arcu accumsan lorem amet accumsan commodo odio cubilia ac eu interdum placerat placerat arcu commodo lobortis adipiscing semper ornare pellentesque.</p>
        <p>Amet nibh adipiscing adipiscing. Commodo ante vis placerat interdum massa massa primis. Tempus condimentum tempus non ac varius cubilia adipiscing placerat lorem turpis at. Aliquet lorem porttitor interdum. Amet lacus. Aliquam lobortis faucibus blandit ac phasellus. In amet magna non interdum volutpat porttitor metus a ante ac neque. Nisi turpis. Commodo col. Interdum adipiscing mollis ut aliquam id ante adipiscing commodo integer arcu amet blandit adipiscing arcu ante.</p>
    </div>
</section>

UmbracoLearning/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

UmbracoLearning/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "='" + property.Value.ToString() + "'");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style='" + string.Join(" ", cssVals) + "'");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

UmbracoLearning/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row);
                    }
                </div>
            }   
        }else { 
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

UmbracoLearning/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "='" + property.Value.ToString() + "'");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style='" + string.Join(" ", cssVals) + "'");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

UmbracoLearning/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

UmbracoLearning/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

UmbracoLearning/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

UmbracoLearning/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.caption">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

UmbracoLearning/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

UmbracoLearning/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();

    markup = markup.Replace("#value#", Model.value.ToString());
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

UmbracoLearning/Views/Partials/Home/Banner.cshtml
<section id="banner">
    <div class="inner">
        <h1>
            Introspect: <span>
                A free + fully responsive<br />
                site template by TEMPLATED
            </span>
        </h1>
        <ul class="actions">
            <li><a href="#" class="button alt">Get Started</a></li>
        </ul>
    </div>
</section>

UmbracoLearning/Views/Partials/Home/SectionOne.cshtml
<section id="one">
    <div class="inner">
        <header>
            <h2>Magna Etiam Lorem</h2>
        </header>
        <p>Suspendisse mauris. Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula. Integer adipiscin sem. Nullam quis massa sit amet nibh viverra malesuada. Nunc sem lacus, accumsan quis, faucibus non, congue vel, arcu, erisque hendrerit tellus. Integer sagittis. Vivamus a mauris eget arcu gravida tristique. Nunc iaculis mi in ante.</p>
        <ul class="actions">
            <li><a href="#" class="button alt">Learn More</a></li>
        </ul>
    </div>
</section>

UmbracoLearning/Views/Partials/Home/SectionThree.cshtml
<section id="three">
    <div class="inner">
        <article>
            <div class="content">
                <span class="icon fa-laptop"></span>
                <header>
                    <h3>Tempus Feugiat</h3>
                </header>
                <p>Morbi interdum mollis sapien. Sed ac risus. Phasellus lacinia, magna lorem ullamcorper laoreet, lectus arcu.</p>
                <ul class="actions">
                    <li><a href="#" class="button alt">Learn More</a></li>
                </ul>
            </div>
        </article>
        <article>
            <div class="content">
                <span class="icon fa-diamond"></span>
                <header>
                    <h3>Aliquam Nulla</h3>
                </header>
                <p>Ut convallis, sem sit amet interdum consectetuer, odio augue aliquam leo, nec dapibus tortor nibh sed.</p>
                <ul class="actions">
                    <li><a href="#" class="button alt">Learn More</a></li>
                </ul>
            </div>
        </article>
        <article>
            <div class="content">
                <span class="icon fa-laptop"></span>
                <header>
                    <h3>Sed Magna</h3>
                </header>
                <p>Suspendisse mauris. Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula.</p>
                <ul class="actions">
                    <li><a href="#" class="button alt">Learn More</a></li>
                </ul>
            </div>
        </article>
    </div>
</section>

UmbracoLearning/Views/Partials/Home/SectionTwo.cshtml
<section id="two">
    <div class="inner">
        <article>
            <div class="content">
                <header>
                    <h3>Pellentesque adipis</h3>
                </header>
                <div class="image fit">
                    <img src="images/pic01.jpg" alt="" />
                </div>
                <p>Cumsan mollis eros. Pellentesque a diam sit amet mi magna ullamcorper vehicula. Integer adipiscin sem. Nullam quis massa sit amet lorem ipsum feugiat tempus.</p>
            </div>
        </article>
        <article class="alt">
            <div class="content">
                <header>
                    <h3>Morbi interdum mol</h3>
                </header>
                <div class="image fit">
                    <img src="images/pic02.jpg" alt="" />
                </div>
                <p>Cumsan mollis eros. Pellentesque a diam sit amet mi magna ullamcorper vehicula. Integer adipiscin sem. Nullam quis massa sit amet lorem ipsum feugiat tempus.</p>
            </div>
        </article>
    </div>
</section>

UmbracoLearning/Views/Partials/SharedLayout/Footer.cshtml
<section id="footer">
    <div class="inner">
        <header>
            <h2>Get in Touch</h2>
        </header>
        <form method="post" action="#">
            <div class="field half first">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" />
            </div>
            <div class="field half">
                <label for="email">Email</label>
                <input type="text" name="email" id="email" />
            </div>
            <div class="field">
                <label for="message">Message</label>
                <textarea name="message" id="message" rows="6"></textarea>
            </div>
            <ul class="actions">
                <li><input type="submit" value="Send Message" class="alt" /></li>
            </ul>
        </form>
        <div class="copyright">
            &copy; Untitled Design: <a href="https://templated.co/">TEMPLATED</a>. Images <a href="https://unsplash.com/">Unsplash</a>
        </div>
    </div>
</section>

UmbracoLearning/Views/Partials/SharedLayout/Header.cshtml
@using UmbracoLearning.Models
@using Umbraco.Web.Models
@inherits Umbraco.Web.Mvc.UmbracoViewPage<List<NavigationList>>
@helper RenderSubItems(List<NavigationList> listItems)
{
    if (listItems != null)
    {
        foreach (var item in listItems)
        {
            <a href="@item.Link.Url" target="@item.Link.Target">@item.Link.Text</a>
            if (item.HasSubNavigation)
            {
                @RenderSubItems(item.NavItems)
            }
        }
    }
}
<header id="header">
    <div class="inner">
        <a href="/" class="logo">introspect</a>
        <nav id="nav">
            @RenderSubItems(Model)
        </nav>
    </div>
</header>

UmbracoLearning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>